public_key = " "
private_key = ""
atlasprojectid=" "
cluster_region "US-EAST-1"
atlas_provider_name "AWS"
atlas_provider_instance_size_name=" "
auto_scaling_disk_gb_enabled = "true"
mongo_db_major_version = "5.0"
mongodb.atlas_databass_username = "chetan"
mangodb.atlas_database_user_password = "Shri@2020"
